### PR TITLE
PReLU and LeakyReLU activations

### PR DESCRIPTION
**Pull request by jac33k**
A minor one, but to test the idea I'm working, I'd need these two activation layers.

## PReLU
Applies element-wise the function PReLU where weight is a learnable parameter.

## LeakyReLU
Applies element-wise, LeakyReLU

### CODE REVIEW

**Comment by ankane** [comment]
Awesome, thanks @jac33k!

**Comment by ankane** [comment]
Also, just pushed a new version (0.1.2) with lots of improvements / fixes, so should be a little less painful if you upgrade. Most of the functionality from [this tutorial](https://pytorch.org/tutorials/beginner/nn_tutorial.html) should be supported.

**Comment by jac33k** [comment]
Great, thanks for the update @ankane!

**Comment by ankane** [comment]
Hey @jac33k, for the next release, I'm planning to relicense the project under the BSD 3-Clause license to match PyTorch (since code will be ported from there).

To be on the safe side, I wanted to get your permission to relicense your contribution under the [BSD 3-Clause license](https://opensource.org/licenses/BSD-3-Clause) (otherwise, will need to back it out). Please let me know. Thanks!

**Comment by jac33k** [comment]
@ankane that’s a good idea, I’m fine with changing the license 👍

**Comment by ankane** [comment]
Great, thanks!

**Pull request merged**
